services:
    Maniax\ContaoPortfolio\EventListener\Contao\DCA\TlManiaxContaoPortfolioItem:
        public: true
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'
            - '@request_stack'
            - '@twig'

    Maniax\ContaoPortfolio\EventListener\Contao\DCA\TlManiaxContaoPortfolioCategory:
        public: true

    # Contao Hooks
    Maniax\ContaoPortfolio\EventListener\Contao\BackendMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -255 }
        arguments:
          - '@router'
          - '@request_stack'

    Maniax\ContaoPortfolio\EventListener\Contao\DCA\TlModule:
        public: true
        arguments: ['@Doctrine\Persistence\ManagerRegistry']
