services:
    Maniax\ContaoJobs\EventListener\Contao\DCA\TlManiaxContaoJobsOffer:
        public: true
        arguments:
            - '@Maniax\ContaoJobs\Helper\EmploymentType'
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'
            - '@request_stack'
            - '@twig'

    Maniax\ContaoJobs\EventListener\Contao\DCA\TlManiaxContaoJobsJobLocation:
        public: true

    Maniax\ContaoJobs\EventListener\Contao\DCA\TlManiaxContaoJobsSettingsEmploymentType:
        public: true
        arguments:
            - '@Maniax\ContaoJobs\Helper\DataTypeMapper'
            - '@Maniax\ContaoJobs\Helper\EmploymentType'

    # Contao Hooks
    Maniax\ContaoJobs\EventListener\Contao\DCA\SetPtableForContentListener:
        tags:
            - { name: contao.hook, hook: loadDataContainer, method: setPtableForContentListener, priority: 0 }
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'

    Maniax\ContaoJobs\EventListener\Contao\BackendMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -255 }
        arguments:
          - '@router'
          - '@request_stack'

    Maniax\ContaoJobs\EventListener\Contao\DCA\TlModule:
        public: true
        arguments: ['@Doctrine\Persistence\ManagerRegistry']
