maniax_contao_jobs.offer_filter:
    path: /_maniax-contao-jobs-basic/offer/filter
    defaults:
        _scope: frontend
        _token_check: false
        _controller: Maniax\ContaoJobs\Controller\JobsOfferFilterRequestController::filterOffersAction

Maniax\ContaoJobs\Controller\Contao\BackendModule\SettingsController:
    path: /contao/maniaxcontaojobs/settings
    defaults:
        _scope: backend
        _controller: Maniax\ContaoJobs\Controller\Contao\BackendModule\SettingsController::showSettings
