services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    contao_jobs.listener.generate_page:
        class: ManiaxAtWork\ContaoJobsBundle\EventListener\GeneratePageListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: generatePage }

    contao_jobs.listener.insert_tags:
        class: ManiaxAtWork\ContaoJobsBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao_jobs.listener.preview_url_convert:
        class: ManiaxAtWork\ContaoJobsBundle\EventListener\PreviewUrlConvertListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_jobs.listener.preview_url_create:
        class: ManiaxAtWork\ContaoJobsBundle\EventListener\PreviewUrlCreateListener
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_jobs.picker.jobs_provider:
        class: ManiaxAtWork\ContaoJobsBundle\Picker\JobsPickerProvider
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@security.helper'
        tags:
            - { name: contao.picker_provider, priority: 128 }
